#!/bin/sh
##### -*- mode:shell-script; indent-tabs-mode:nil; sh-basic-offset:2 -*-
# Copyright (c) 2017 Travis Cross <tc@traviscross.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

concat=false
bitrate_v="768k"
bitrate_a="96k"
format="all"
framerate="29.97"
resolution=""
while getopts "a:cf:m:r:v:" o; do
  case "$o" in
    a) bitrate_a="$OPTARG" ;;
    c) concat=true ;;
    f) format="$OPTARG" ;;
    m) framerate="$OPTARG" ;;
    r) resolution="$OPTARG" ;;
    v) bitrate_v="$OPTARG" ;;
  esac
done
shift $(($OPTIND-1))

if [ $# -lt 1 ]; then
  echo "usage: $0 [-c] <in-files> ...">&2
  echo "  [-r <resolution>]">&2
  exit 1
fi

res_a=""
case "$resolution" in
  480) res_a="hd480" res_n="480p" ;;
  720) res_a="hd720" res_n="720p" ;;
  1080) res_a="hd1080" res_n="1080p" ;;
  2048) res_a="2k" res_n="2048p" ;;
  4096) res_a="4k" res_n="4096p" ;;
esac

compress () {
  local ai="" if="$1"
  if $concat; then
    local tmp="$(mktemp)"
    for x in "$@"; do
      echo "file '$(pwd)/$x'" >> "$tmp"
    done
    ai="-f concat -i $tmp"
  else
    ai="-i $1"
  fi
  echo "## ai: $ai">&2
  res_arg=""; test -z "$res_a" || res_arg="-s $res_a"
  res_sf=""; test -z "$res_n" || res_sf="_${res_n}"
  #parallel -j2 --progress <<EOF
  if test "$format" = all -o "$format" = webm; then
    schedtool -D -e ffmpeg $ai -y \
      $res_arg \
      -r "$framerate" \
      -c:v libvpx \
      -crf 10 \
      -b:v "$bitrate_v" \
      -c:a libvorbis \
      -ar 48000 \
      -b:a "$bitrate_a" \
      "${if%.*}_${res_n}_wq.webm"
  fi
  if test "$format" = all -o "$format" = mp4; then
    schedtool -D -e ffmpeg $ai -y \
      $res_arg \
      -r "$framerate" \
      -c:v h264 \
      -profile:v baseline \
      -movflags faststart \
      -b:v "$bitrate_v" \
      -c:a aac \
      -ar 48000 \
      -b:a "$bitrate_a" \
      "${if%.*}${res_sf}_wq.mp4"
  fi
#EOF
  rm -f "$tmp"
}

if $concat; then
  compress "$@"
else
  for if in "$@"; do
    compress "$if"
  done
fi
